#模式 balance(均衡模式)、parallel(平行模式)
mode: parallel
#容器
containers:
  - address: http://192.168.31.233:5700
    #用户名
    username: admin
    #密码
    password: admin
    #权重 balance模式下权重越高分得的ck越多，默认1
    weigth: 3
    #单独对容器进行模式设置
    mode: parallel
  - address: http://192.168.31.233:5525
    username: admin
    password: admin
    #本地配置文件路径
  - path: /Users/cdle/Desktop/jd_study/jdc/config.sh
  - path: /Users/cdle/Desktop/jd_study/jdc/list.sh
#自定义二维码页面，支持本地、网络路径
qrcode: 
#静态文件 便于自定义二维码页面时，引入css、js等文件
static: ./static
#管理员账户pin，有多个用'&'拼接
master: 
#数据库位置
database: "./.jdc.db"
